// AUTO-GENERATED. DO NOT EDIT.
// Generated from Config-Schema-1.2.json

import Foundation

package enum GeneratedKeys {
  package static let topKeys: [String] = [
    "CoreSecurity",
    "DiagnosticsAudit",
    "Environment",
    "Firewall",
    "Location",
    "LoginWindow",
    "Org",
    "PerUser",
    "PowerManagement",
    "SSH",
    "ScreenSaver",
    "Sharing",
    "System",
    "TimeNTP",
  ]

  package static let modeKeys: Set<String> = Set([
    "CoreSecurity.CheckARStatus",
    "CoreSecurity.CheckFileVaultStatus",
    "CoreSecurity.CheckGateKeeperStatus",
    "CoreSecurity.CheckSIPStatus",
    "CoreSecurity.UpdateXProtect",
    "DiagnosticsAudit.ConfigureAuditFlagsCore",
    "DiagnosticsAudit.DisableDiagnosticData",
    "DiagnosticsAudit.EnableAuditFailureHalt",
    "DiagnosticsAudit.EnableSecurityAuditing",
    "DiagnosticsAudit.LimitAuditRecordsAccess",
    "DiagnosticsAudit.RetainInstallLog",
    "Environment.RequireDirectoryService",
    "Environment.RequireMDMEnrollment",
    "Environment.RequireSecurityAgent",
    "Firewall.EnableFirewall",
    "Firewall.EnableFirewallAllowSigned",
    "Firewall.EnableFirewallBlockAllIncoming",
    "Firewall.EnableFirewallStealthMode",
    "Location.EnableLocationServices",
    "LoginWindow.DisableAutomaticLogin",
    "LoginWindow.DisableFastUserSwitching",
    "LoginWindow.DisableGuestAccessToShares",
    "LoginWindow.DisableGuestUser",
    "LoginWindow.DisablePasswordHints",
    "LoginWindow.EnableLibraryValidation",
    "LoginWindow.EnableLoginWindowSecurityBanner",
    "LoginWindow.EnableSSHLoginBanner",
    "LoginWindow.EnableSudoCommandLogging",
    "LoginWindow.EnforceSudoTimestampTypeTTY",
    "LoginWindow.ForceAdminPWForPreferences",
    "LoginWindow.ForceLoginWindowFullName",
    "LoginWindow.RemoveGuestHomeFolder",
    "LoginWindow.SetSudoTimeout",
    "PerUser.DisableAdTracking",
    "PerUser.DisableAirDrop",
    "PerUser.DisableBluetoothSharing",
    "PerUser.DisableMediaSharing",
    "PerUser.DisableSafariDownloadAutoRun",
    "PerUser.DisableSiri",
    "PerUser.EnableTerminalSecureKeyboard",
    "PerUser.ForceShowFileNameExtensions",
    "PerUser.ForceShowWifiStatus",
    "PerUser.LockLoginKeychain",
    "PerUser.RemoveUserPasswordHints",
    "PerUser.SecureHomeFolders",
    "PowerManagement.DestroyFileVaultKeyOnStandby",
    "PowerManagement.DisablePowerNap",
    "PowerManagement.DisableWOMP",
    "PowerManagement.ForceHibernateOnSleep",
    "SSH.ConfigureSSHClientAliveCountMax",
    "SSH.ConfigureSSHClientAliveInterval",
    "SSH.DisableSSHPasswordAuthentication",
    "ScreenSaver.RequirePasswordOnWake",
    "ScreenSaver.SetScreenSaverDelay",
    "Sharing.DisableBonjourAdvertising",
    "Sharing.DisableContentCaching",
    "Sharing.DisableDVDSharing",
    "Sharing.DisableFileSharing",
    "Sharing.DisableHTTPServer",
    "Sharing.DisableInternetSharing",
    "Sharing.DisableNFSServer",
    "Sharing.DisablePrinterSharing",
    "Sharing.DisableRemoteAppleEvents",
    "Sharing.DisableRemoteLogin",
    "Sharing.DisableRemoteManagement",
    "Sharing.DisableScreenSharing",
    "System.CheckSystemUptime",
  ])

  package static let parameterKeys: Set<String> = Set([
    "Environment.ExpectedSecurityProducts",
    "LoginWindow.SecurityBannerText",
    "LoginWindow.SudoTimeout",
    "Org.OrgContact",
    "Org.OrgName",
    "PerUser.AirDropAutoDisableMinutes",
    "PerUser.LockKeychainInactivity",
    "SSH.SSHClientAliveCountMax",
    "SSH.SSHClientAliveInterval",
    "ScreenSaver.ScreenSaverDelay",
    "ScreenSaver.ScreenSaverPasswordDelay",
    "System.SystemUptimeMaxDays",
    "System.SystemUptimeWarnDays",
    "TimeNTP.DefaultTimeZone",
    "TimeNTP.ForceTimeServer",
    "TimeNTP.TimeServer",
  ])
}