#!/bin/bash
set -euo pipefail

VERSION_DIR="${1:?version dir missing}"
OUT_SWIFT="${2:?output swift path missing}"

# ----------------------------
# You control these 3 knobs:
# ----------------------------
# 0=v1, 1=v2, 2=v3 ...
MAJOR_INDEX_FILE="${VERSION_DIR}/major_index"
# A=.0, B=.1, C=.2 ...
MINOR_LETTER_FILE="${VERSION_DIR}/minor_letter"
# Channel/Seed letter: m..a or empty for release
CHANNEL_FILE="${VERSION_DIR}/channel"

# Local build counter
BUILD_FILE="${VERSION_DIR}/build_number"

# Defaults (first run)
[[ -f "$MAJOR_INDEX_FILE" ]] || echo "1" > "$MAJOR_INDEX_FILE"     # jump to v2
[[ -f "$MINOR_LETTER_FILE" ]] || echo "A" > "$MINOR_LETTER_FILE"
[[ -f "$CHANNEL_FILE" ]] || echo "m" > "$CHANNEL_FILE"
[[ -f "$BUILD_FILE" ]] || echo "0" > "$BUILD_FILE"

MAJOR_INDEX="$(cat "$MAJOR_INDEX_FILE" | tr -d '[:space:]')"
MINOR_LETTER="$(cat "$MINOR_LETTER_FILE" | tr -d '[:space:]')"
CHANNEL="$(cat "$CHANNEL_FILE" | tr -d '[:space:]')"
BUILD="$(cat "$BUILD_FILE" | tr -d '[:space:]')"

# Increment build number
BUILD=$((BUILD + 1))
echo "$BUILD" > "$BUILD_FILE"

# Convert minor letter to number: A->0, B->1, ...
# bash: get ASCII code
ord() { LC_CTYPE=C printf '%d' "'$1"; }
A_ORD=$(ord "A")
L_ORD=$(ord "$MINOR_LETTER")
MINOR_NUM=$((L_ORD - A_ORD))
if [[ $MINOR_NUM -lt 0 ]]; then MINOR_NUM=0; fi

# Marketing version: (major_index+1).minor_num
MARKETING_MAJOR=$((MAJOR_INDEX + 1))
MARKETING_VERSION="${MARKETING_MAJOR}.${MINOR_NUM}"

# Label: 1A42m (channel may be empty)
LABEL="${MAJOR_INDEX}${MINOR_LETTER}${BUILD}${CHANNEL}"

# Write Swift
cat > "$OUT_SWIFT" <<EOF
// Auto-generated by Tools/gen_version.sh — DO NOT EDIT.
import Foundation

package enum NotaryVersion {
  package static let majorIndex: Int = ${MAJOR_INDEX}         // 0=v1, 1=v2, ...
  package static let minorLetter: String = "${MINOR_LETTER}"  // A=.0, B=.1, ...
  package static let build: Int = ${BUILD}                    // local counter
  package static let channel: String = "${CHANNEL}"           // m..a or "" for release

  package static let marketingVersion: String = "${MARKETING_VERSION}" // e.g. 2.0
  package static let label: String = "${LABEL}"                          // e.g. 1A42m
}
EOF

# Write Make override for pkg version (must be numeric)
cat > "${VERSION_DIR}/version.mk" <<EOF
# Auto-generated — DO NOT EDIT.
VERSION := ${MARKETING_VERSION}
BUILD_LABEL := ${LABEL}
EOF

echo "Generated version: ${LABEL} (pkg VERSION=${MARKETING_VERSION})"
